# Setup
title: Onur Serin
url: https://serinonur.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-S5VLEEKLXF

# Specify the author for blog posts
author:
  name: Onur Serin
  url: https://twitter.com/kyresse_
  email: work@onurserin.co

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: Case Study
    url: /case-study

  - title: About
    url: /about
